# Generated by Django 5.2.8 on 2025-11-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_demanddata_route_driver_current_latitude_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DemandData",
        ),
    ]
